/*
 Esta es la ventana en la que se van a registrar los clientes 
para poder tener una lista de ellos
 */
package xemlet.presentacion;

/**
 *
 * @author fcoav, Javier Shaka, Jesus Arce, Monica Paola
 * Ahora se debe agregar lo que se importe
 */

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import mx.itson.xemlet.nucleo.entidades.Cliente;




public class registrarClientes extends javax.swing.JInternalFrame {
/**
 * En esta parte es donde se instancia la lista, el cliente y el modelo de la tabla
 */
    
    ArrayList<Cliente> ListaC = new ArrayList<Cliente>();
    Cliente Coco = new Cliente();
  
    public registrarClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Txtnumtel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Txtdom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Txtid = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tblclientes = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        btndele = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("Nombre del cliente");

        jLabel2.setText("Numero de teléfono");

        jLabel3.setText("Domicilio");

        jLabel4.setText("Numero de suscriptor");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 3));

        Tblclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre del cliente", "Numero de télefono", "Domicilio", "Numero de suscriptor"
            }
        ));
        jScrollPane1.setViewportView(Tblclientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnadd.setText("Agregar");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btndele.setText("Eliminar");
        btndele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(TxtNombre)
                        .addComponent(jLabel2)
                        .addComponent(Txtnumtel)
                        .addComponent(jLabel3)
                        .addComponent(Txtdom, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(Txtid))
                    .addComponent(btnadd)
                    .addComponent(btndele))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txtnumtel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txtdom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btndele)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        
        Coco.setNombre(TxtNombre.getText());
        Coco.setNumeroTelefonico(Txtnumtel.getText());
        Coco.setDomicilio(Txtdom.getText());
        Coco.setIdCliente(Integer.parseInt(Txtid.getText()));
        
        ListaC.add(Coco);
        
        Entablar();
        
        TxtNombre.setText(null);
        Txtnumtel.setText(null);
        Txtdom.setText(null);
        Txtid.setText(null);
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleActionPerformed
     DefaultTableModel Layla = (DefaultTableModel) Tblclientes.getModel();
     Layla.removeRow(Tblclientes.getSelectedRow());
             
    }//GEN-LAST:event_btndeleActionPerformed

    /**
     * Este Metodo es para agregar columnas a la tabla, por eso se llama
     * Entablar
     */
    public void Entablar(){
        String Matriz[][] = new String[ListaC.size()][4];
        
        for (int Elsa = 0; Elsa < ListaC.size(); Elsa++) {
            
            Matriz[Elsa][0] = ListaC.get(Elsa).getNombre();
            Matriz[Elsa][1] = ListaC.get(Elsa).getNumeroTelefonico();
            Matriz[Elsa][2] = ListaC.get(Elsa).getDomicilio();
            Matriz[Elsa][3] = String.valueOf(ListaC.get(Elsa).getIdCliente());
            
        }
        Tblclientes.setModel(new javax.swing.table.DefaultTableModel(
        Matriz, 
                new String[]{
                "Nombre", "Numero Teléfonico", "Domicilio", "Numero de Suscriptor"
                }
        ));
    }
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tblclientes;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField Txtdom;
    private javax.swing.JTextField Txtid;
    private javax.swing.JTextField Txtnumtel;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndele;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
