/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.xemlet.presentacion;

import mx.itson.xemlet.nucleo.controlador.ControladorFrameRegistro;

/**
 *
 * @author javiershaka
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Factura
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        //manda a llamar el controdalor del frame para que sea llenado con los datos
        new ControladorFrameRegistro().llenarFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbLlamadasMovil = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbLlamadasFijas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtRegistroCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtLlamadasRealizadasFijas = new javax.swing.JTextField();
        txtNombrePaquete = new javax.swing.JTextField();
        txtLlamadasFijas = new javax.swing.JTextField();
        txtMinutosACelular = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtNoTelefonico = new javax.swing.JTextField();
        txtCostoAdicionalLlamada = new javax.swing.JTextField();
        txtLlamadasRealizadasMovil = new javax.swing.JTextField();
        txtCostoAdicionalMinutos = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtLlamadasRealizadas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbLlamadasMovil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Fecha", "Duracion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbLlamadasMovil);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 238, 400, 200));

        tbLlamadasFijas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Fecha", "Duracion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbLlamadasFijas);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 238, 400, 200));

        jLabel1.setText("Datos del cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 15, -1, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 81, -1, -1));

        jLabel3.setText("Numero de registro");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 55, -1, -1));

        jLabel4.setText("Numero telefonico:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 107, -1, -1));

        jLabel5.setText("Datos del paquete");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 15, -1, -1));

        jLabel6.setText("Nombre:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 55, -1, -1));

        jLabel7.setText("Llamadas fijas:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 81, -1, -1));

        jLabel8.setText("Minutos A celular");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 107, -1, -1));

        jLabel9.setText("Precio:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 133, -1, -1));

        jLabel10.setText("Historial");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 180, -1, -1));

        jLabel11.setText("Llamadas fijas");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 218, -1, -1));

        jLabel12.setText("Llamadas Moviles");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 218, -1, -1));

        jLabel13.setText("Llamadas realizadas");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, 20));

        jLabel14.setText("Minutos");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, -1, -1));

        jLabel15.setText("Costo adicional");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, -1));

        jLabel16.setText("Costo adicional");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, -1, -1));

        txtRegistroCliente.setEditable(false);
        getContentPane().add(txtRegistroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 52, 200, -1));

        txtNombreCliente.setEditable(false);
        getContentPane().add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 78, 200, -1));

        txtLlamadasRealizadasFijas.setEditable(false);
        getContentPane().add(txtLlamadasRealizadasFijas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 101, -1));

        txtNombrePaquete.setEditable(false);
        getContentPane().add(txtNombrePaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 52, 200, -1));

        txtLlamadasFijas.setEditable(false);
        getContentPane().add(txtLlamadasFijas, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 78, 200, -1));

        txtMinutosACelular.setEditable(false);
        getContentPane().add(txtMinutosACelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 104, 200, -1));

        txtPrecio.setEditable(false);
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 130, 200, -1));

        txtNoTelefonico.setEditable(false);
        getContentPane().add(txtNoTelefonico, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 104, 200, -1));

        txtCostoAdicionalLlamada.setEditable(false);
        getContentPane().add(txtCostoAdicionalLlamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 101, -1));

        txtLlamadasRealizadasMovil.setEditable(false);
        getContentPane().add(txtLlamadasRealizadasMovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 101, -1));

        txtCostoAdicionalMinutos.setEditable(false);
        getContentPane().add(txtCostoAdicionalMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 101, -1));

        jLabel17.setText("Llamadas realizadas:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 133, -1, -1));

        txtLlamadasRealizadas.setEditable(false);
        getContentPane().add(txtLlamadasRealizadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 130, 200, -1));

        jButton1.setText("Facturar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 516, -1, -1));

        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/xemlet/presentacion/imagenes/simple_blue_wallpaper_by_x0oaurao0x-d3hvcxj.jpg"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //crea una nueva instancia del frame factura y lo hace visible
        FrameFactura factura = new FrameFactura(this, true);
        factura.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // se hace invisible esta ventana
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTable tbLlamadasFijas;
    public static javax.swing.JTable tbLlamadasMovil;
    public static javax.swing.JTextField txtCostoAdicionalLlamada;
    public static javax.swing.JTextField txtCostoAdicionalMinutos;
    public static javax.swing.JTextField txtLlamadasFijas;
    public static javax.swing.JTextField txtLlamadasRealizadas;
    public static javax.swing.JTextField txtLlamadasRealizadasFijas;
    public static javax.swing.JTextField txtLlamadasRealizadasMovil;
    public static javax.swing.JTextField txtMinutosACelular;
    public static javax.swing.JTextField txtNoTelefonico;
    public static javax.swing.JTextField txtNombreCliente;
    public static javax.swing.JTextField txtNombrePaquete;
    public static javax.swing.JTextField txtPrecio;
    public static javax.swing.JTextField txtRegistroCliente;
    // End of variables declaration//GEN-END:variables
}
